### PR TITLE
[Gssoc'21] Added a Project description Page

### LINKED ISSUE #5: Full description of a project
When an user clicks on the more option then they can check the full details including the description, screenshots of the project and how to contact the owner of the project for collaboration.

image

### PR DESCRIPTION
**Pull request by arpit456jain**
INCLUDE ALL NECESSARY FIELDS AND DELETE FIELDS THAT ARE NOT NECESSARY.

Added a Project description Page in this page all the information to he project is listed

Fixes #5 

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
I am uploading a video in cmnt

### CODE REVIEW

**Comment by rupeshmohanty** [comment]
@arpit456jain Please upload the video for this PR.

**Comment by arpit456jain** [comment]
> @arpit456jain Please upload the video for this PR.

Yes it's uploading net is slow that's it is taking time

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/115121301-91514080-9fcf-11eb-8e9e-38dddeb9920e.mp4

sorry for the delay

**Comment by arpit456jain** [comment]
I had try to made the UI interface good looking as much as i can I searched for any free template for it but i couldn't find it 
I will surely enhance the UI in any other issue .
I had already spend 4 to 5 hours in this issue and and i think its enough for now the functionality is working fine from my side .
If there is any changes to be done in feature please let me know

**Comment by arpit456jain** [comment]
@sakshi300699 @ishubham21 @anika-001 kindly review my PR

**Comment by arpit456jain** [comment]
@rupeshmohanty should i update the sql file also ?

**Comment by rupeshmohanty** [comment]
> @rupeshmohanty should i update the sql file also ?

Are there any changes in the database?

**Comment by arpit456jain** [comment]
> > @rupeshmohanty should i update the sql file also ?
> 
> Are there any changes in the database?

I just added 2 projects for Demonstration for the video that's it

**Review by ishubham21 — APPROVED** [review]

**Comment by arpit456jain** [comment]
Thanks @ishubham21 
@sakshi300699 @anika-001 kindly review my PR

**Review by anika-001 — APPROVED** [review]

**Review by sakshi300699 — APPROVED** [review]

**Comment by arpit456jain** [comment]
> > > @rupeshmohanty should i update the sql file also ?
> > 
> > 
> > Are there any changes in the database?
> 
> I just added 2 projects for Demonstration for the video that's it

@rupeshmohanty  kindly review my PR.

**Comment by rupeshmohanty** [comment]
> > > @rupeshmohanty should i update the sql file also ?
> > 
> > 
> > Are there any changes in the database?
> 
> I just added 2 projects for Demonstration for the video that's it

If there is no change in the configuration of the database, then it's not needed!

**Comment by arpit456jain** [comment]
> > > > @rupeshmohanty should i update the sql file also ?
> > > 
> > > 
> > > Are there any changes in the database?
> > 
> > 
> > I just added 2 projects for Demonstration for the video that's it
> 
> If there is no change in the configuration of the database, then it's not needed!

Ok thanks @rupeshmohanty

**Pull request merged**
