### PR TITLE
Gssoc'21 Added the Password validation by js in Register page

### LINKED ISSUE #53: Gssoc'21 Password validation by js in Register page
**Is your feature request related to a problem? Please describe.**
Password validation by js in Register page is required for secured and strong password.
**Describe the solution you'd like**
It will look some thing like this.
les

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by arpit456jain**
INCLUDE ALL NECESSARY FIELDS AND DELETE FIELDS THAT ARE NOT NECESSARY.

### Description
Well there is no validations in form in front-end so I add some validations and a confirm password field also.

Fixes #53 

### Type of Change:
**Delete irrelevant options.**

- Code
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

Kindly watch this video completely.

https://user-images.githubusercontent.com/55352601/113487446-ca6cb980-94d5-11eb-8b52-4dcdf9a0de6c.mp4

### CODE REVIEW

**Comment by arpit456jain** [comment]
@sakshi300699 kindly review my PR

**Comment by sakshi300699** [comment]
> 
> 
> @sakshi300699 kindly review my PR

Would be doing it shortly.

**Review by ishubham21 — CHANGES_REQUESTED** [review]
Though the functionality works super fine, it would be a great addition if you could remove both the 'console.log' statements in this PR since they aren't considered as good practices to write the code.

Further, you can change the innerText of message2 to 'Passwords didn't match' when the validation fails, this would enhance the User Experience.

**Review by ishubham21 — APPROVED** [review]

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/113541018-fcc60600-95fe-11eb-8768-7a9d591d64cc.mp4

**Comment by arpit456jain** [comment]
thanks @ishubham21  .
@sakshi300699 @anika-001 kindly review my PR.

**Review by anika-001 — APPROVED** [review]

**Review by sakshi300699 — APPROVED** [review]

**Comment by arpit456jain** [comment]
Thank you @sakshi300699 @anika-001 for approving.
@rupeshmohanty kindly review it

**Pull request merged**
