### PR TITLE
[Gssoc'21] Added the dark mode with toggle button

### LINKED ISSUE #75: [GSSoC'21] adding dark mode with toggle button
I want to add a dark mode to the website as i had already raised this issue before and made a PR but by mistake i closed the PR and issue was also closed i had already added this feature to website just had to make a PR

### PR DESCRIPTION
**Pull request by arpit456jain**
INCLUDE ALL NECESSARY FIELDS AND DELETE FIELDS THAT ARE NOT NECESSARY.

### Description
Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.

https://user-images.githubusercontent.com/55352601/114260828-c28ca800-99f4-11eb-8b1e-ec624b85f562.mp4

Fixes #75 

### Type of Change:
**Delete irrelevant options.**
- Code
- Quality Assurance
- User Interface

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Uploaded a video above

### CODE REVIEW

**Comment by arpit456jain** [comment]
@rupeshmohanty kindly review my PR

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/114261238-1bf5d680-99f7-11eb-8691-e99453fbb16c.mp4

I just notice that find project partner button was not working in dark mode so i had fixed it.

**Comment by arpit456jain** [comment]
@sakshi300699 @ishubham21 kindly review my PR

**Review by ishubham21 — CHANGES_REQUESTED** [review]
Hi, I feel that this is getting quite dull when dark mode is toggled on. You can work to make sure the colors remain as bright as they were. 
Further,  dark mode isn't just the black color as you've specified it to be. Dark mode has standard color codes (fixed so that the contrast doesn't strain the users in fact should be relaxing) . 
You can search "Standard color for dark mode" on google. 
Rest let's ask what everyone feels. @rupeshmohanty @sakshi300699 @anika-001

**Comment by arpit456jain** [comment]
@ishubham21 actually there is a img on main page (index.php) I can't change its color so i had added a on it just like a black layer .
If you want I will remove it no issues. and I will try to make color contrast better

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/114270551-a0158180-9a2a-11eb-907d-4e4a0db6349d.mp4

@ishubham21 check now

**Review by ishubham21 — APPROVED** [review]

**Comment by arpit456jain** [comment]
Thanks @ishubham21 .
@sakshi300699 @anika-001 kindly review my PR

**Review by sakshi300699 — APPROVED** [review]

**Review by anika-001 — APPROVED** [review]
Looks great!

**Comment by arpit456jain** [comment]
Thanks @anika-001 

@rupeshmohanty kindly review it

**Pull request merged**
