### PR TITLE
organized_code

### LINKED ISSUE #59: Organized Code!
Whenever other contributor want to contribute new feature then he/she have to repeat code of header, footer, navbar and modal.

Solution: There should be separate files for header, footer, navbar and modal in components folder.

### PR DESCRIPTION
**Pull request by asmitsirohi**
I Organized the code of Dashboard, because Whenever other contributor want to contribute new feature then he/she have to repeat code of header, footer, navbar and modal.

Solution: I break the code of Explore/index.php file into header.php, footer.php, navbar.php, modals.php files which is present in      components/common folder.

fixes #59

Here is the demonstrated video :

https://user-images.githubusercontent.com/63240102/113553207-08242c00-9615-11eb-8273-3e69f7156d6b.mp4

### CODE REVIEW

**Review by sakshi300699 — COMMENTED** [review]
@asmitsirohi  Could u send a screenshot or a video recording of the code that you changed in the footer.php file?

**Comment by asmitsirohi** [comment]
@sakshi300699 mam, Here is screenshot of footer.php file
image

**Comment by sakshi300699** [comment]
@asmitsirohi Shouldn't the footer code be in this file?

**Comment by asmitsirohi** [comment]
@sakshi300699 mam, Actually there is no code for footer is present in Explore/index.php file. I just created footer.php for future reference.

**Comment by asmitsirohi** [comment]
It showing "This branch has conflicts that must be resolved", Can you please specify me what is the conflict.

image

**Comment by sakshi300699** [comment]
@asmitsirohi  Check the conflicted files mentioned. Explore/index.php file

**Comment by asmitsirohi** [comment]
@sakshi300699 mam, I resolved the conflict. Please Check it now.

**Comment by sakshi300699** [comment]
Sure! @asmitsirohi

**Review by ishubham21 — APPROVED** [review]

**Review by sakshi300699 — APPROVED** [review]

**Review by anika-001 — APPROVED** [review]

**Pull request merged**
