### PR TITLE
Fixed Issue#68 Added Primary Key Constraint to contact table

### PR DESCRIPTION
**Pull request by hardikvarshney**
INCLUDE ALL NECESSARY FIELDS AND DELETE FIELDS THAT ARE NOT NECESSARY.

### Description
Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.

Fixes # [ISSUE]

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

### CODE REVIEW

**Comment by hardikvarshney** [comment]
Screenshot (79)_LI

**Comment by hardikvarshney** [comment]
Everything is working fine.


https://user-images.githubusercontent.com/76947310/114135174-7ffc9a00-9926-11eb-9e67-886744f91af8.mp4

**Comment by hardikvarshney** [comment]
@rupeshmohanty please add the level of issue(i.e. level 2) on this PR. And kindly review it.

**Comment by hardikvarshney** [comment]
@sakshi300699 @ishubham21 @anika-001 Please review this PR so that I can go ahead with designing admin dashboard.

**Comment by hardikvarshney** [comment]
@sakshi300699 @ishubham21 @anika-001 It's been two days none of the mentor has reviewed my PR. Why is it so..???. If there is any problem in my PR please let me know.

**Comment by sakshi300699** [comment]
@hardikvarshney We are sorry for the delay, we are a process of reviewing this PR.

**Review by sakshi300699 — CHANGES_REQUESTED** [review]
Capture


@hardikvarshney This error is being displayed in admin/header.php file. Please fix this.

**Pull request closed without merging**
