### PR TITLE
Resolved bug and resized logo

### LINKED ISSUE #112: Hover Effect, Bug, Logo size
Describe the issue: 1. he navbar looks simple, this can be more creative and effective for user experience to add hover in navbar.
2. The content of landing page is mixing with image, the last two lines of content is going to mislead image.
3. Size of logo of website is too small then navbar at least and other content of website.

How to reproduce the issue: **I can add hover in navbar, Fix bug, can increase the size of logo so that logo can be seen easly.**

Proof of issue(Screenshot/Location where to find the issue): **Mention where to find the issue, also attach proof of issues is available**
image

Bug :
image

Please assign this issue to me under gssoc21.

### PR DESCRIPTION
**Pull request by RuchiGitHu**
INCLUDE ALL NECESSARY FIELDS AND DELETE FIELDS THAT ARE NOT NECESSARY.

### Description
I have resized logo and resolved bug.

Fixes #112 

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
The result of modification is given below.
image
image

### CODE REVIEW

**Comment by RuchiGitHu** [comment]
> INCLUDE ALL NECESSARY FIELDS AND DELETE FIELDS THAT ARE NOT NECESSARY.
> 
> ### Description
> I have resized logo and resolved bug.
> 
> Fixes #112
> 
> ### Type of Change:
> **Delete irrelevant options.**
> 
> * Code
> * Quality Assurance
> * User Interface
> 
> **Code/Quality Assurance Only**
> 
> * Bug fix (non-breaking change which fixes an issue)
> 
> ### How Has This Been Tested?
> The result of modification is given below.
> image
> image

Please review @anika-001 @ishubham21

**Comment by ishubham21** [comment]
> > INCLUDE ALL NECESSARY FIELDS AND DELETE FIELDS THAT ARE NOT NECESSARY.
> > ### Description
> > I have resized logo and resolved bug.
> > Fixes #112
> > ### Type of Change:
> > **Delete irrelevant options.**
> > 
> > * Code
> > * Quality Assurance
> > * User Interface
> > 
> > **Code/Quality Assurance Only**
> > 
> > * Bug fix (non-breaking change which fixes an issue)
> > 
> > ### How Has This Been Tested?
> > The result of modification is given below.
> > image
> > image
> 
> Please review @anika-001 @ishubham21

Hi @RuchiGitHu!  I feel that this logo is quite too big. Can you please change the height to 80px and width to 160/170px and see if that works?

**Comment by RuchiGitHu** [comment]
> > > INCLUDE ALL NECESSARY FIELDS AND DELETE FIELDS THAT ARE NOT NECESSARY.
> > > ### Description
> > > I have resized logo and resolved bug.
> > > Fixes #112
> > > ### Type of Change:
> > > **Delete irrelevant options.**
> > > 
> > > * Code
> > > * Quality Assurance
> > > * User Interface
> > > 
> > > **Code/Quality Assurance Only**
> > > 
> > > * Bug fix (non-breaking change which fixes an issue)
> > > 
> > > ### How Has This Been Tested?
> > > The result of modification is given below.
> > > image
> > > image
> > 
> > 
> > Please review @anika-001 @ishubham21
> 
> Hi @RuchiGitHu! I feel that this logo is quite too big. Can you please change the height to 80px and width to 160/170px and see if that works?

Please review @ishubham21 @anika-001, I have made changes as requested.
image

**Review by ishubham21 — APPROVED** [review]

**Review by anika-001 — APPROVED** [review]

**Comment by RuchiGitHu** [comment]
Please let me know what next after this!!
Thanks for support..

**Pull request merged**
