### PR TITLE
Fixes Issue#64 Added Admin Dashboard showing number of users, projects and messages …

### PR DESCRIPTION
**Pull request by hardikvarshney**
https://user-images.githubusercontent.com/76947310/114814011-ea9f5100-9dd0-11eb-9f38-f6edad17d786.mp4

### CODE REVIEW

**Comment by hardikvarshney** [comment]
@rupeshmohanty please mention level of issue(i.e. level 3) on this PR and kindly review it.

**Review by sakshi300699 — CHANGES_REQUESTED** [review]
@hardikvarshney , you have made all the required changes. However a change needs to be made....
Since you are making the changes in the Database and then it's reflected in the admin dashboard. This will work fine in local machine but not when hosted as it would be difficult to make changes directly from Database.
So please make a UI form for that in the dashboard itself, which upon submission automatically updated the Database and hence the dashboard.

**Comment by hardikvarshney** [comment]
> @hardikvarshney , you have made all the required changes. However a change needs to be made....
> Since you are making the changes in the Database and then it's reflected in the admin dashboard. This will work fine in local machine but not when hosted as it would be difficult to make changes directly from Database.
> So please make a UI form for that in the dashboard itself, which upon submission automatically updated the Database and hence the dashboard.

@sakshi300699 These form has already been created.

**Comment by hardikvarshney** [comment]
> > @hardikvarshney , you have made all the required changes. However a change needs to be made....
> > Since you are making the changes in the Database and then it's reflected in the admin dashboard. This will work fine in local machine but not when hosted as it would be difficult to make changes directly from Database.
> > So please make a UI form for that in the dashboard itself, which upon submission automatically updated the Database and hence the dashboard.
> 
> @sakshi300699 These form has already been created.


https://user-images.githubusercontent.com/76947310/114967325-e129ed80-9e91-11eb-9d68-2f152b1b84ac.mp4

**Comment by rupeshmohanty** [comment]
@hardikvarshney Wouldn't it be better to see the messages in the admin dashboard?

**Comment by hardikvarshney** [comment]
> @hardikvarshney Wouldn't it be better to see the messages in the admin dashboard?

It would be more better to to have separate link for it because I have decided something else for blank part on dashboard.

**Comment by hardikvarshney** [comment]
@sakshi300699 @ishubham21 @anika-001 Please review my PR

**Review by sakshi300699 — APPROVED** [review]

**Review by ishubham21 — APPROVED** [review]

**Review by anika-001 — APPROVED** [review]

**Pull request merged**
