### PR TITLE
Added Contributor

### LINKED ISSUE #17: Adding Contributor section in readme  ( Automatically )
I will like to add a feature this will update contributor list in read me automatically !! Will start to work on this issue as soon as i get assigend !!

### PR DESCRIPTION
**Pull request by rohank2502**
INCLUDE ALL NECESSARY FIELDS AND DELETE FIELDS THAT ARE NOT NECESSARY.

### Description
Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.

Fixes  #17 

### Type of Change:
**Delete irrelevant options.**

- Code
- Documentation

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

I have check it in my readme file

### CODE REVIEW

**Review by rupeshmohanty — APPROVED** [review]

**Review by sakshi300699 — APPROVED** [review]
Looks cool!

**Review by anika-001 — APPROVED** [review]
Looks nice!

**Review by ishubham21 — COMMENTED** [review]
For the first line, you can replace 'Contributor' with 'Contributors'. 
And for the second line, I don't think it's required. 
What do you say @rohank2502?

**Comment by ishubham21** [comment]
> INCLUDE ALL NECESSARY FIELDS AND DELETE FIELDS THAT ARE NOT NECESSARY.
> 
> ### Description
> Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.
> 
> Fixes #17
> 
> ### Type of Change:
> **Delete irrelevant options.**
> 
> * Code
> * Documentation
> 
> ### How Has This Been Tested?
> Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.
> 
> I have check it in my readme file

Also, @rohank2502, from the next time, try to include screenshots of whatever changes you perform in the PR. This would help us to review your PRs faster.

**Comment by rohank2502** [comment]
> 
> 
> > INCLUDE ALL NECESSARY FIELDS AND DELETE FIELDS THAT ARE NOT NECESSARY.
> > ### Description
> > Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.
> > Fixes #17
> > ### Type of Change:
> > **Delete irrelevant options.**
> > 
> > * Code
> > * Documentation
> > 
> > ### How Has This Been Tested?
> > Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.
> > I have check it in my readme file
> 
> Also, @rohank2502, from the next time, try to include screenshots of whatever changes you perform in the PR. This would help us to review your PRs faster.

Ok for sure !!

**Comment by rohank2502** [comment]
Done !!

**Comment by rohank2502** [comment]
> 
> 
> Looks cool!

Thanks

**Comment by rohank2502** [comment]
> 
> 
> Looks nice!

Thanks

**Pull request merged**
