### PR TITLE
Improve Ui of Project cards

### LINKED ISSUE #34: UI Improvement ("Project Idea" Card)
**Describe the bug**
The "Project Idea" Card is too simple. It can have a project repository icon, also social media handles of the project idea raiser for further communication, also the card UI can be improved to match the whole UI of the page.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 89.0

### PR DESCRIPTION
**Pull request by arpit456jain**
### Description
1.Improved Ui of Project cards
2. There was a bug in place of image of project it was showing the image of profile pic

Fixes #34 

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
cards

### CODE REVIEW

**Comment by arpit456jain** [comment]
@rupeshmohanty kindly add labels to it i.e level3 as I had solved 2 issues in one

**Review by ishubham21 — APPROVED** [review]

**Comment by arpit456jain** [comment]
@sakshi300699 @anika-001 kindly review my PR

**Review by anika-001 — APPROVED** [review]

**Comment by arpit456jain** [comment]
> @rupeshmohanty kindly add labels to it i.e level3 as I had solved 2 issues in one

@rupeshmohanty please add labels to it

**Review by sakshi300699 — APPROVED** [review]

**Comment by arpit456jain** [comment]
@rupeshmohanty kindly give it a level 3 labels i had solved 2 issue in this PR i can make 2 PR of level 2 for that but i thought it will save time

**Comment by rupeshmohanty** [comment]
@arpit456jain What's the second issue you fixed?

**Comment by arpit456jain** [comment]
> @arpit456jain What's the second issue you fixed?

Previously it was showing the profile picture in place of project image i can upload a video of my master branch

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/116269233-abdba480-a79b-11eb-9f40-08397d9cd6ac.mp4

@rupeshmohanty you can see this video in this video i have dispayed the 2nd issue when i am on previous master branch how its showing profile pic in place of project img

**Comment by rupeshmohanty** [comment]
@arpit456jain That profile image was needed to see which user posted that blog, so it was not a bug actually, but the thing you have implemented here is a part of the whole issue i.e. "Improving the UI of the card".

**Comment by arpit456jain** [comment]
Ok

**Pull request merged**
