### PR TITLE
Complete Info of loggedin User! 

### LINKED ISSUE #58: Complete Info of loggedin User!
There should be a option available, where logged in user can change his/her username or GitHub link or LinkedIn link or Bio or DP. 
Also, there should be a separate page where user can monitor all his/her profile.

To solve this issue there should be new page "user_info.php" attached with user's name at navigation bar, where users can manage their profile.

image

### PR DESCRIPTION
**Pull request by asmitsirohi**
I have made a separate page where users can view their profile and also update their profile.
I have made a new page "user_info.php" attached with user's name at navigation bar, where users can manage their profile.

Fixes #58 

Here is a screenshot of new page
Screenshot_2021-04-17 LesKollab - User Info

### CODE REVIEW

**Comment by rupeshmohanty** [comment]
@asmitsirohi Can you make a video for the functioning of this feature and share here!

**Comment by asmitsirohi** [comment]
@rupeshmohanty sir, Here is video....


https://user-images.githubusercontent.com/63240102/115987729-ea266780-a5d3-11eb-9d8c-703a85e6402a.mp4

**Review by anika-001 — APPROVED** [review]

**Review by ishubham21 — APPROVED** [review]

**Review by sakshi300699 — APPROVED** [review]

**Comment by rupeshmohanty** [comment]
@asmitsirohi This PR has some conflicts, please fix them.

**Comment by asmitsirohi** [comment]
@rupeshmohanty sir, I resolved the conflict.

**Comment by rupeshmohanty** [comment]
@asmitsirohi Yes nice work!

**Pull request merged**
