### PR TITLE
[Gssoc'21] Enhance the footer as much as possible

### LINKED ISSUE #73: [Gssoc'21] Imporve the footer
**Is your feature request related to a problem? Please describe.**
I want to improve the ui/ux of footer as it is currently very dull.

### PR DESCRIPTION
**Pull request by arpit456jain**
INCLUDE ALL NECESSARY FIELDS AND DELETE FIELDS THAT ARE NOT NECESSARY.

The footer was looking very dull previously .
prev1
prev2

Fixes #73 

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface

**Code/Quality Assurance Only**

- New feature : Cool social media icons

### How Has This Been Tested?

https://user-images.githubusercontent.com/55352601/114375644-81d29180-9ba2-11eb-87c1-473b0464e6a9.mp4

### CODE REVIEW

**Comment by arpit456jain** [comment]
@sakshi300699 @ishubham21 @anika-001 kindly review my PR.

and please add labels of gssoc and level 3 (if possible) If you like my work its very time taking to make it responsive in both screens (Desktop and mobile)

Dont't worry of extra social media icon i will remove that one which will be unnecessary

**Comment by rupeshmohanty** [comment]
@arpit456jain This PR is for which issue?

**Comment by arpit456jain** [comment]
> @arpit456jain This PR is for which issue?

@rupeshmohanty its for issue #73 
I had also mentioned this is PR creation

**Comment by arpit456jain** [comment]
I had improved the footer. Added a wave feature and social media icons with animation in footer and make them responsive as you can see previously the footer was not responsive in mobile view

**Comment by arpit456jain** [comment]
After this pr i will immediately open a pr for 404 page the work is already has been done.
But i prefer to work on a single pr at a time

**Comment by rupeshmohanty** [comment]
@arpit456jain Okay cool!

**Review by sakshi300699 — APPROVED** [review]
Awesome Work!

**Comment by arpit456jain** [comment]
> Awesome Work!

Thank you @sakshi300699 

@ishubham21  @anika-001 kindly review my PR

**Review by ishubham21 — APPROVED** [review]

**Review by anika-001 — APPROVED** [review]

**Comment by arpit456jain** [comment]
thanks @anika-001 @ishubham21 

@rupeshmohanty kindly review my PR

**Pull request merged**
