### PR TITLE
Issue#62 "Added login functionality for admin."

### PR DESCRIPTION
**Pull request by hardikvarshney**
https://user-images.githubusercontent.com/76947310/113541882-ba052d80-9600-11eb-9fdf-4d06ce21fbed.mp4

### CODE REVIEW

**Comment by rupeshmohanty** [comment]
Create an issue for Dashboard page too.

**Comment by sakshi300699** [comment]
@hardikvarshney This branch has conflicts. Please fix that

**Comment by hardikvarshney** [comment]
> Create an issue for Dashboard page too.

I have already created Issue for "Dashboard" i.e. Issue#64

**Comment by hardikvarshney** [comment]
> @hardikvarshney This branch has conflicts. Please fix that

Merge Conflict Fixed.

**Review by sakshi300699 — APPROVED** [review]

**Review by anika-001 — APPROVED** [review]

**Comment by hardikvarshney** [comment]
@ishubham21 please review my PR so that it can be merged.

**Review by ishubham21 — APPROVED** [review]

**Pull request merged**
