### PR TITLE
[Gssoc'21] Added Faq's section in index.php

### LINKED ISSUE #88: (GSSOC 21)Faq section
**Is your feature request related to a problem? Please describe.**

There is very less information about the website and the goal of the website , how to add Project because until a user is logged in he is not able to see the page to add Project

**Describe the solution you'd like**
I would like to add a faq section just below about section you can add the question and ans to it 

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by arpit456jain**
INCLUDE ALL NECESSARY FIELDS AND DELETE FIELDS THAT ARE NOT NECESSARY.

### Description
Added the FAQs section in index.php just under about section

Fixes #88 

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface

**Code/Quality Assurance Only**

- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
I am uploading a video in comment section

### CODE REVIEW

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/114746358-4801b680-9d6d-11eb-9456-07df92bed9d3.mp4

**Comment by arpit456jain** [comment]
@rupeshmohanty kindly add the same labels which are on the issue

**Comment by arpit456jain** [comment]
@sakshi300699 @ishubham21 @anika-001 kindly review my PR

**Review by anika-001 — APPROVED** [review]
Looks great!

**Comment by arpit456jain** [comment]
> Looks great!

Thanks @anika-001 😃

@sakshi300699 @ishubham21 kindly review my PR

**Review by ishubham21 — APPROVED** [review]

**Review by sakshi300699 — APPROVED** [review]

**Comment by arpit456jain** [comment]
Thanks @sakshi300699 @ishubham21 

@rupeshmohanty kindly review my PR

**Pull request merged**
