### PR TITLE
[Gssoc'21] Added show Password feature

### LINKED ISSUE #61: [Gssoc'21] show password button
**Is your feature request related to a problem? Please describe.**
There must be a show password button in both login/signup.

**Describe the solution you'd like**
I can add that and write some js for it.

### PR DESCRIPTION
**Pull request by arpit456jain**
INCLUDE ALL NECESSARY FIELDS AND DELETE FIELDS THAT ARE NOT NECESSARY.

I had added the show password feature in both login and register

Fixes #61 

### Type of Change:
**Delete irrelevant options.**

- Code
- User Interface

**Code/Quality Assurance Only**

- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

I am uploading a video.

https://user-images.githubusercontent.com/55352601/113602744-9ffb3780-9660-11eb-8b89-ed9e9c6819f5.mp4

### CODE REVIEW

**Comment by arpit456jain** [comment]
@sakshi300699 kindly review my PR.

**Comment by arpit456jain** [comment]
kindly review my PR.

**Comment by arpit456jain** [comment]
@anika-001 kindly review my PR

**Review by ishubham21 — APPROVED** [review]

**Review by sakshi300699 — APPROVED** [review]

**Review by anika-001 — APPROVED** [review]

**Comment by arpit456jain** [comment]
Thanks @anika-001 .
@rupeshmohanty kindly review it

**Pull request merged**
