### PR TITLE
pull updated version and done required changes

### LINKED ISSUE #40: (gsoc'21)  Mess in the responsiveness in phone view
**Describe the bug**
There is a total mess in the phone view.
Navbar is messed up. button is messed up and background image is also messed up in short almost whole page is messed up in phone view . It is looking like this in phone view.
les1
les2
les3

**To Reproduce**

**Expected behavior**
It should fully responsive in all screen 
**Screenshots**
I have to work on it currently i am unable to give any screenshots but if you assign me this i will give my best and will make it responsive as much as possible for screen as soon as possible . I am a gsoc'21 participant , kindly assign me this.
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by arpit456jain**
pull updated version and done required changes

### Description
There was a total mess in responsiveness in mobile view previously it was looking like this
les3
les2
les1

now my code is looking like this

**IN Desktop View**
screencapture-localhost-LesKollab-index-php-2021-03-21-14_12_32
In Phone View
screencapture-localhost-LesKollab-index-php-2021-03-21-14_12_59

https://user-images.githubusercontent.com/55352601/112039301-ea14f100-8b69-11eb-8262-922d305b475b.mp4

Fixes #40 

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
I had uploaded a video to show how its looking

### CODE REVIEW

**Comment by arpit456jain** [comment]
Thank You @sakshi300699 mam

**Comment by arpit456jain** [comment]
@sakshi300699  mam Please merge this PR before merging another otherwise i had to the changes again 😅

**Review by sakshi300699 — APPROVED** [review]

**Review by anika-001 — APPROVED** [review]

**Comment by arpit456jain** [comment]
@ishubham21 please review it sir.

**Comment by arpit456jain** [comment]
@ishubham21  sir please review it before any conflicts occur again

**Review by ishubham21 — APPROVED** [review]

**Comment by arpit456jain** [comment]
Thank you @ishubham21 sir

**Comment by arpit456jain** [comment]
@sakshi300699 mam please merge it

**Comment by arpit456jain** [comment]
@rupeshmohanty sir please merge this PR 😅

**Pull request merged**
