### PR TITLE
schema is updated, import new schema(loskollab.sql) in localhost

### PR DESCRIPTION
**Pull request by Raghad-Khaled**
INCLUDE ALL NECESSARY FIELDS AND DELETE FIELDS THAT ARE NOT NECESSARY.

### Description
Here is change for schema (leskolab.sql) and index.php and post-project
improve the schema (add new relation in SQL ) solve #18 issue

### You should import the new file leskolab.sql in localhost

 **here is the old stacks in schema**
Old

# After changes
 
 **here the stack table**

Stack

 **also the relation between stack and project**

P_S

### CODE REVIEW

**Comment by rupeshmohanty** [comment]
The code has some bugs for example the variables have not been declared properly. Here is an example:

image

**Comment by Raghad-Khaled** [comment]
please can you clear more which variables have not been declared properly

**Comment by sakshi300699** [comment]
@Raghad-Khaled Could you please add a video demonstrating how the changes made by you is working. It would be easy for us to review.

**Comment by Raghad-Khaled** [comment]
https://user-images.githubusercontent.com/60848147/113482140-8493ff00-949d-11eb-89db-c3902be10828.mp4

@sakshi300699 
@rupeshmohanty 
now I think it is clear and I hope it my PR accepted :)

**Comment by rupeshmohanty** [comment]
@Raghad-Khaled I don't see any difference in the output except the database configuration. How is the new configuration better than the previous one?

**Comment by Raghad-Khaled** [comment]
@rupeshmohanty 
The previous configuration on Relation Project is not in 1NF (First-Normal-Form) because of multi-valued attribute tags
and in the article in the link show my opinion 
https://www.geeksforgeeks.org/first-normal-form-1nf/
as the database schema should be normalized.

**Comment by rupeshmohanty** [comment]
@Raghad-Khaled 
This branch has some issues. Please fix them

**Comment by Raghad-Khaled** [comment]
@rupeshmohanty 
do you mean schema branch 
and what issues should be fixed?

**Comment by sakshi300699** [comment]
@Raghad-Khaled you need to fix the conflict in this branch that you have created, otherwise this PR wouldn't be able to be merged.

**Comment by Raghad-Khaled** [comment]
@sakshi300699 
Okay, now conflicts is fixed 
thank you ^^

**Review by sakshi300699 — APPROVED** [review]
This is working fine!

**Review by anika-001 — APPROVED** [review]
Great work!

**Review by ishubham21 — APPROVED** [review]

**Pull request merged**
