### PR TITLE
Fixes Issue#92 Added View Messages functionality in admin panel

### PR DESCRIPTION
**Pull request by hardikvarshney**
https://user-images.githubusercontent.com/76947310/116026990-68851700-a671-11eb-9b8d-14b456146985.mp4

### CODE REVIEW

**Comment by hardikvarshney** [comment]
@rupeshmohanty Please mention the level of the issue(i.e. level 2) and kindly review it.

**Review by ishubham21 — COMMENTED** [review]
What are you using the reply button for? I guess it's just for opening the gmail, right?

**Comment by hardikvarshney** [comment]
> What are you using the reply button for? I guess it's just for opening the gmail, right?

Yes, admin can give reply from Gmail by copying the email address of user from table.

**Comment by ishubham21** [comment]
> > What are you using the reply button for? I guess it's just for opening the gmail, right?
> 
> Yes, admin can give reply from Gmail by copying the email address of user from table.

I guess instead of the link that you've put in, this link would work - https://mail.google.com/mail/?view=cm&fs=1&to=ishubham2101@gmail.com.
This link is referencing my e-mail address and can be changed to reference different e-mail addresses.

**Comment by hardikvarshney** [comment]
> > > What are you using the reply button for? I guess it's just for opening the gmail, right?
> > 
> > 
> > Yes, admin can give reply from Gmail by copying the email address of user from table.
> 
> I guess instead of the link that you've put in, this link would work - https://mail.google.com/mail/?view=cm&fs=1&to=ishubham2101@gmail.com.
> This link is referencing my e-mail address and can be changed to reference different e-mail addresses.



> > > What are you using the reply button for? I guess it's just for opening the gmail, right?
> > 
> > 
> > Yes, admin can give reply from Gmail by copying the email address of user from table.
> 
> I guess instead of the link that you've put in, this link would work - https://mail.google.com/mail/?view=cm&fs=1&to=ishubham2101@gmail.com.
> This link is referencing my e-mail address and can be changed to reference different e-mail addresses.

Yes we can do that. It is more easier than copying email address.

**Comment by hardikvarshney** [comment]
@ishubham21 now you can review.

**Review by ishubham21 — APPROVED** [review]
Approving these changes now but will have to change this to make it universal later. I mean not all use gmail. Some also use their work emails without configuring them for gmail.

**Review by rupeshmohanty — APPROVED** [review]

**Review by anika-001 — APPROVED** [review]

**Pull request merged**
