### PR TITLE
Added 'About us' in index.php

### LINKED ISSUE #15: About Us page missing
In the nav-bar the About Us link is unresponsive.
Can create a modal or create a link to new page or add further block of div element in the landing page itself

### PR DESCRIPTION
**Pull request by CoderGaurav01**
### Description
Added AboutUs section in index.php.

Fixes #15

### CODE REVIEW

**Review by sakshi300699 — CHANGES_REQUESTED** [review]
@CoderGaurav01 The About Us section text is fine, but the repeated background image should be changed.

**Comment by CoderGaurav01** [comment]
Changed the background and styling 

image

**Review by sakshi300699 — APPROVED** [review]
Looks Great!

**Review by ishubham21 — APPROVED** [review]

**Review by anika-001 — APPROVED** [review]

**Comment by sakshi300699** [comment]
@rupeshmohanty I think this PR can be merged, if you approve with this. Also tags needs to be added to the PR as well.

**Comment by rupeshmohanty** [comment]
> @rupeshmohanty I think this PR can be merged, if you approve with this. Also tags needs to be added to the PR as well.

Yeah let me merge this PR

**Comment by CoderGaurav01** [comment]
Great

**Pull request merged**
