### PR TITLE
[Gssoc'21] Added Contact Us section

### LINKED ISSUE #54: Contact Us section
**Is your feature request related to a problem? Please describe.**
There should be a contact us page or section in website where user  can contact if he/she have any query. with validations

**Describe the solution you'd like**
I can make a separate page or add it in same page 
**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by arpit456jain**
### Description
I had added a contact us button in navbar.
And a modal with contact us form.
with little bit of backend in PHP.
Fixes #54 

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

Contact Us section Added

### How Has This Been Tested?
I am attaching a video for this.

https://user-images.githubusercontent.com/55352601/112940024-2805ac80-914a-11eb-8324-87e837f3d40e.mp4

### CODE REVIEW

**Comment by arpit456jain** [comment]
@rupeshmohanty I had also added backend in php for contact us section. kindly add labels of gssoc'21 and **level3**  as it was a very challenging task for me to add backend.
I am attaching a video in next comment with full working

**Comment by arpit456jain** [comment]
here is the video.

https://user-images.githubusercontent.com/55352601/112949216-981a2f80-9156-11eb-9d77-bc96eeaca813.mp4

**Comment by arpit456jain** [comment]
@rupeshmohanty kindly review it and add labels before merging

**Comment by arpit456jain** [comment]
@anika-001 @sakshi300699 @ishubham21  please review my PR.

**Review by sakshi300699 — CHANGES_REQUESTED** [review]
The UI is looking fine but since changes are also done to the database, you need to update the sql file too.

**Comment by sakshi300699** [comment]
@arpit456jain As you have made another table named contact in phpmyadmin. You need to update that in the already present leskollab.sql file with the chnages you have made.
So basically everything is good, just add your sql file in the repo.

**Comment by arpit456jain** [comment]
> @arpit456jain As you have made another table named contact in phpmyadmin. You need to update that in the already present leskollab.sql file with the changes you have made.
> So basically everything is good, just add your sql file in the repo.

oh ok ok got it @sakshi300699 done.

**Review by sakshi300699 — APPROVED** [review]
@arpit456jain This is working perfectly well!

**Comment by arpit456jain** [comment]
@ishubham21 @anika-001 kindly review my PR.

**Review by anika-001 — APPROVED** [review]

**Review by ishubham21 — APPROVED** [review]
Works fine.

**Pull request merged**
