### PR TITLE
[Gssoc] Added the Back to top button

### LINKED ISSUE #96: [Gssoc'21] Back to top button
**Is your feature request related to a problem? Please describe.**

As our website is getting bigger it should have a back to top button with smooth scrolling.
I would like to add it.

**Additional context**

### PR DESCRIPTION
**Pull request by arpit456jain**
Added the Back to top button in index.php

Fixes #96 

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface

**Code/Quality Assurance Only**

- New feature (non-breaking change which adds functionality pre-approved by mentors)

https://user-images.githubusercontent.com/55352601/115104418-db0d3d00-9f75-11eb-8704-c646d15a8c30.mp4

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

### CODE REVIEW

**Comment by arpit456jain** [comment]
@sakshi300699 @ishubham21 @anika-001 kindly review my PR

**Review by ishubham21 — CHANGES_REQUESTED** [review]
Can you please move all the CSS in index.php to a dedicated CSS file?

**Comment by arpit456jain** [comment]
> Can you please move all the CSS in index.php to a dedicated CSS file?

let me try

**Comment by arpit456jain** [comment]
> Can you please move all the CSS in index.php to a dedicated CSS file?

@ishubham21 its done 
should i make a video sample for it??

**Review by ishubham21 — APPROVED** [review]

**Review by anika-001 — APPROVED** [review]

**Review by sakshi300699 — APPROVED** [review]

**Comment by arpit456jain** [comment]
@rupeshmohanty  kindly review my Pr

**Pull request merged**
