### PR TITLE
Project Details Ui Enhanced 

### LINKED ISSUE #9: Add check-project.php Page
**Is your feature request related to a problem?**
Have a create the check-project.php page. It will show the full information of the project. 

**Describe the solution you'd like**
The Check-project.php page will have the full details related to the project.

**Describe alternatives you've considered**
No other alternative.

**Additional context**
Line 129 in Explore/index.php for **More...** about the project.

Assign to me. @rupeshmohanty

### PR DESCRIPTION
**Pull request by arpit456jain**
INCLUDE ALL NECESSARY FIELDS AND DELETE FIELDS THAT ARE NOT NECESSARY.

### Description
I had tried to enhance the UI of Project Description Page

Fixes #9 

**Code/Quality Assurance Only**

- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

https://user-images.githubusercontent.com/55352601/115412686-2cd1f380-a212-11eb-995a-4f66551a1daf.mp4

### CODE REVIEW

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/115414218-7a9b2b80-a213-11eb-8381-b05856344214.mp4

Improve it a little bit more

**Comment by arpit456jain** [comment]
@rupeshmohanty kindly review my PR

**Comment by arpit456jain** [comment]
@sakshi300699 @ishubham21 @anika-001 kindly review my PR

**Review by ishubham21 — APPROVED** [review]
Nice work!

**Review by anika-001 — APPROVED** [review]

**Review by sakshi300699 — APPROVED** [review]

**Comment by arpit456jain** [comment]
@rupeshmohanty kindly review my PR

**Pull request merged**
