### PR TITLE
fix the responsiveness of the index.php

### LINKED ISSUE #40: (gsoc'21)  Mess in the responsiveness in phone view
**Describe the bug**
There is a total mess in the phone view.
Navbar is messed up. button is messed up and background image is also messed up in short almost whole page is messed up in phone view . It is looking like this in phone view.
les1
les2
les3

**To Reproduce**

**Expected behavior**
It should fully responsive in all screen 
**Screenshots**
I have to work on it currently i am unable to give any screenshots but if you assign me this i will give my best and will make it responsive as much as possible for screen as soon as possible . I am a gsoc'21 participant , kindly assign me this.
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by arpit456jain**
INCLUDE ALL NECESSARY FIELDS AND DELETE FIELDS THAT ARE NOT NECESSARY.

### Description
There was a total mess in responsiveness in mobile view previously it was looking like this
les1
les2
les3

now my code is looking like this
**IN Desktop View**
screencapture-localhost-LesKollab-index-php-2021-03-21-14_12_32

**In Phone View**
screencapture-localhost-LesKollab-index-php-2021-03-21-14_12_59

https://user-images.githubusercontent.com/55352601/111899206-112bcf80-8a51-11eb-88f8-562bc87e8901.mp4

Fixes #40 

### Type of Change:
**Delete irrelevant options.**

- Code
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.
 I had attached a sample video.

I hope you like it and it was enough to merge it.

### CODE REVIEW

**Comment by arpit456jain** [comment]
@sakshi300699 mam Is there any Problem in this PR. If not Please make sure to add the gssoc'21 label before merging it.

**Comment by arpit456jain** [comment]
@sakshi300699 mam please merge this PR

**Comment by sakshi300699** [comment]
@arpit456jain the PA would be merging this as soon as the mentors and PA approve of this.

**Review by anika-001 — APPROVED** [review]

**Review by sakshi300699 — APPROVED** [review]

**Comment by arpit456jain** [comment]
gssco

@sakshi300699 mam I hope It doesn't create any problem

**Comment by sakshi300699** [comment]
Nope @arpit456jain don't worry, that's not an issue

**Review by ishubham21 — APPROVED** [review]

**Comment by arpit456jain** [comment]
@sakshi300699  mam I have no idea why this is showing conflicts my code is working fine.
what should I do?

**Comment by sakshi300699** [comment]
@arpit456jain your branch is not up-to-date with the master branch, you need to pull all the changes to this branch.

**Comment by arpit456jain** [comment]
ok mam let me try

**Comment by arpit456jain** [comment]
@sakshi300699  mam I had pull the latest code and done the required changes again so I am creating a another PR with that...

Please add the labels of level2 and gssoc21 sorry for the inconvenience but please this time merge it as soon as possible I request 
 
Again My code is working fine and fully responsive no problem occur 
I had just removed the **inline CSS** with **Internal Css and add some media query** that's it.

Is that ok?
Can i create another PR. I will close this

**Comment by sakshi300699** [comment]
Okay @arpit456jain Please close this PR.

**Comment by arpit456jain** [comment]
ok mam

**Pull request closed without merging**
