### PR TITLE
Confirmation alert Before Logout

### LINKED ISSUE #104: Confirmation Alert for Logout
I would like to add a confirmation alert for logout , like when user click on logout a alert will pop up like this
sweet alert

and it will ask  **Are You  sure You want to logout **  there will be two options cancel or Yes , Logout

### PR DESCRIPTION
**Pull request by arpit456jain**
INCLUDE ALL NECESSARY FIELDS AND DELETE FIELDS THAT ARE NOT NECESSARY.

### Description
I have added a confirmation alert for logout , like when user click on logout a alert will pop up and it will ask **Are You sure You want to logout ** there will be two options cancel or Yes , Logout

Fixes #104 

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

https://user-images.githubusercontent.com/55352601/115506714-d0fe7d80-a298-11eb-869a-9288b6ca2aa3.mp4

### CODE REVIEW

**Review by anika-001 — APPROVED** [review]

**Review by sakshi300699 — APPROVED** [review]

**Review by ishubham21 — COMMENTED** [review]
Hi @arpit456jain could you please confirm that this change wouldn't create a conflict with the PR#102? I'm asking you to do so since both the PRs have worked upon logout functionality.

**Comment by arpit456jain** [comment]
> Hi @arpit456jain could you please confirm that this change wouldn't create a conflict with the PR#102? I'm asking you to do so since both the PRs have worked upon logout functionality.

Hey @ishubham21  May be it will cause merge conflicts but no problem will pull the latest code and will merge in this branch and will also upload a video for confirmation 👍

**Comment by arpit456jain** [comment]
Hey @ishubham21 i just cross check again in pr #102 he edit the files related to admin and i had put this feature for normal user in Explore/index.php 
So i don't think so there will be any merge conflicts

**Comment by ishubham21** [comment]
> Hey @ishubham21 i just cross check again in pr #102 he edit the files related to admin and i had put this feature for normal user in Explore/index.php
> So i don't think so there will be any merge conflicts

Okay! Thanks for the confirmation.

**Review by ishubham21 — APPROVED** [review]

**Pull request merged**
