### PR TITLE
[Gssoc21]Added the 404 page and the code to handle 404 eror

### LINKED ISSUE #72: [Gssoc'21] 404 page
**Is your feature request related to a problem? Please describe.**
There was no 404 page .
I want to make a 404.html page for website

### PR DESCRIPTION
**Pull request by arpit456jain**
INCLUDE ALL NECESSARY FIELDS AND DELETE FIELDS THAT ARE NOT NECESSARY.

### Description
There was no 404 page .

Fixes #72 

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance

**Code/Quality Assurance Only**

- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

https://user-images.githubusercontent.com/55352601/114566274-ba03ce00-9c8f-11eb-9eb6-8a3b1126e7a7.mp4

### CODE REVIEW

**Comment by arpit456jain** [comment]
@rupeshmohanty kindly review my PR and add the labels which are on the issue.

**Comment by arpit456jain** [comment]
lescolab

**Comment by arpit456jain** [comment]
@ishubham21 @sakshi300699 kindly review my PR

**Review by anika-001 — APPROVED** [review]
Looks great!

**Comment by arpit456jain** [comment]
> Looks great!

Thanks a lot @anika-001

**Review by ishubham21 — APPROVED** [review]

**Comment by arpit456jain** [comment]
Thanks @ishubham21 .🙂

@sakshi300699 kindly review my PR

**Review by sakshi300699 — APPROVED** [review]

**Pull request merged**
